### ISSUE TITLE
Add tests & deps

### ISSUE THREAD

**Issue by browniebroke** [eviweb/cookiecutter-template#5]
Is this project still maintained? When I used it I found that the output lacked a couple of things:

- Dependency management (`requirements.txt` or `Pipfile`)
- Tests, with an example using the [pytest plugin](https://github.com/hackebrot/pytest-cookies)
- CI setup: Circle CI or Travis CI

Happy to send over a PR with what I've done, let me know if you have any opinion on the above options. Thanks

**Comment by eviweb** [comment]
Hi @browniebroke,
thanks for your feedback.
Unfortunately, I do not have any time to go on this project for now.
So if you have any PR to share do not hesitate, I will give it a look and merge it if all is ok.

**Comment by browniebroke** [comment]
Thank you for your answer. I appreciate that you might not have the bandwidth for that, no worries. 

I'll see if I can put something together in the next coming weeks.
